# Generated by Django 3.2 on 2025-02-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
