# Generated by Django 3.0.8 on 2025-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencing', '0002_remove_room_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
